### ISSUE TITLE
Wrong paths for windows environment and PROD mode

### ISSUE THREAD

**Issue by gazeciarz** [wigahluk/play-webpack#4]
Hello,

I think there are 2 potential fixes in this great template.
1. /build.sbt -

> val appPath = if (isWin) "app\\frontend" else "./app/frontend"

 instead of

> val appPath = if (isWin) "\\app\\frontend" else "./app/frontend"

2. /app/controllers/Application.scala

> assets.at("/public/bundles", file)

instead of

> assets.at("public/bundles", file)

I can do pull request if You want.

**Comment by wigahluk** [comment]
Hello @gazeciarz, I have no Windows machine to test at hand, so if you can test these paths, please feel free to do a pull request, I'll merge it ASAP.

Thanks for your help! :)

**Comment by wigahluk** [comment]
Thanks @gazeciarz, closing this as #5 is merged now.
